# Generated by Django 4.2.4 on 2023-09-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0002_remove_agency_first_name_remove_agency_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_persons', models.IntegerField()),
                ('names_of_persons', models.CharField(max_length=300)),
                ('tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tourism.tour')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
